CREATE DATAFILE '/oracle/oradata/orabase/USTLV01.dbf' SIZE 1G;
CREATE DATAFILE '/oracle/oradata/orabase/USTLV02.dbf' SIZE 1G;
CREATE DATAFILE '/oracle/oradata/orabase/USTLV03.dbf' SIZE 1G;

CREATE TABLESPACE USTLV DATAFILE ’/oracle/oradata/orabase/USTLV01.dbf’,’/oracle/oradata/orabase/USTLV02.dbf’,’/oracle/oradata/orabase/USTLV03.dbf’;

CREATE USER USTLV100
IDENTIFIED BY "PASSWORD"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS
PROFILE DEFAULT
ACCOUNT UNLOCK;