DROP TABLE IF EXISTS Audio;

CREATE TABLE Audio (
  CODAUDIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DNICLI VARCHAR(15),
  NOMCLI VARCHAR(40),
  APEPATCLI VARCHAR(40),
  APEMATCLI VARCHAR(40),
  TLFNOCLI VARCHAR(9),
  SKILL VARCHAR(10),
  VDN VARCHAR(10),
  FECVENTA TIMESTAMP,  
  PROC VARCHAR(3),
  RUTAAUDIO VARCHAR(200),
  DNIASESOR VARCHAR(15),
  CODEMPRESA INT NOT NULL,
   FECCREA TIMESTAMP,
  FECMOD TIMESTAMP,
  USRCREA VARCHAR(40),
  USRMOD VARCHAR(40)
);