DROP TABLE IF EXISTS Empresa;

 CREATE TABLE Empresa (
  CODEMPRESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOM VARCHAR(40),
  CARPETA VARCHAR(200),
  STS VARCHAR(1),
  FECCREA TIMESTAMP,
  FECMOD TIMESTAMP,
  USRCREA VARCHAR(40),
  USRMOD VARCHAR(40)
  
);