CREATE SEQUENCE USTLV100.SEC_USUARIO_EMPRESA MINVALUE 1 START WITH 1
    INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE USTLV100.SEC_EMPRESA MINVALUE 1 START WITH 1
    INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE USTLV100.SEC_AUDIO MINVALUE 1 START WITH 1
    INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE USTLV100.SEC_AUD_SISTEMA MINVALUE 1 START WITH 1
    INCREMENT BY 1 NOCACHE;

