DROP TABLE IF EXISTS Aud_Sistema;

CREATE TABLE Aud_Sistema (
  CODAUDSIST INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USR VARCHAR(40),
  FEC TIMESTAMP,
  ACCION VARCHAR(200),
  DETALLE VARCHAR(500),
  FECCREA TIMESTAMP,
  FECMOD TIMESTAMP,
  USRCREA VARCHAR(40),
  USRMOD VARCHAR(40)
  
);