DROP TABLE IF EXISTS usuario_empresa;

CREATE TABLE usuario_empresa (
  CODUSREMPRESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USR VARCHAR(40),
  CODEMPRESA INT NOT NULL,
 FECCREA TIMESTAMP,
  FECMOD TIMESTAMP,
  USRCREA VARCHAR(40),
  USRMOD VARCHAR(40)
);